version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data/livestate:/app/data/livestate
      - ./data/statearchive:/app/data/statearchive
      - ./data/schemaarchive:/app/data/schemaarchive
      - ./data/liveschema:/app/data/liveschema
      - ./data/dicts:/app/data/dicts
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://user:password@postgres:5432/deltachanges
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: deltachanges
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/deltachanges:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d deltachanges"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  deltachanges:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/deltachanges

  statearchive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/archive

  schemaarchive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/schemaarchive

  liveschema:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/liveschema
